pipeline {
  agent any
  stages {
    stage('code') {
      steps{
	  git url: "https://github.com/Yatingambhir85/jenkins-demo-task.git", branch: 'main'
   }    
    }
    stage('Build') {
      steps {
	echo "Building docker image"
	    script {
                    def dockerImage = docker.build('my-practice-image:latest', '-f first-pipeline-demo/Dockerfile .')
                }
      }
    }
    stage('Creation') {
	steps {
	  echo "Now creating the container"
	  	script {
			def dockerContainer = dockerImage.run('-p 8080:80 -itd')
			// Storing the docker container ID
			env.CONTAINER_ID = dockerContainer.id
  }
}
  }
}
}


