pipeline {
  agent any
  stages {
    stage('code') {
      steps{
	  git url: "https://github.com/Yatingambhir85/jenkins-demo-task.git", branch: 'main'
   }    
    }
    stage('Build') {
      steps {
	echo "Building docker image"
        sh 'docker build -t my-image -f first-pipeline-demo/Dockerfile .'
      }
    }
    stage('Creation') {
	steps {
	  echo "Now creating the container"
	  sh 'docker run -itd --name my-container -p 8080:80 my-image'
  }
}
  }
}

